import type { Metadata, Viewport } from "next";
import { JetBrains_Mono, Manrope } from "next/font/google";
import { LiquidFilters } from "@/components/fx/liquid-filter";
import { JsonLd, organizationJsonLd, webSiteJsonLd } from "@/components/seo/json-ld";
import { ORG, SITE_DESCRIPTION, SITE_NAME, SITE_TITLE, SITE_URL } from "@/lib/site";
import { SOCIAL_IMAGE } from "@/lib/seo";
import { THEME_BOOTSTRAP, THEME_COLOR } from "@/lib/theme";
import "./globals.css";

/* Both faces are variable fonts: omitting `weight` ships one woff2 per family
   covering the whole range instead of N static instances. `fallback` carries
   the stack tokens/typography.css declares; next/font prepends a
   metric-adjusted local fallback to keep CLS at zero.

   Manrope and JetBrains Mono are the brand faces (Brand Guidelines v1.0,
   08 / Typography). They are rebound onto the design-system variable names in
   globals.css. */
const manrope = Manrope({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-manrope",
  fallback: ["system-ui", "-apple-system", "Segoe UI", "sans-serif"],
});

const jetbrainsMono = JetBrains_Mono({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-jetbrains-mono",
  fallback: ["ui-monospace", "SFMono-Regular", "Menlo", "monospace"],
});

/* Search-console verification tokens are read from the environment so the
   repo never carries them. See SEO_roadmap.txt for where to get each one. */
const verification: Metadata["verification"] = {
  ...(process.env.NEXT_PUBLIC_GSC_VERIFICATION
    ? { google: process.env.NEXT_PUBLIC_GSC_VERIFICATION }
    : {}),
  ...(process.env.NEXT_PUBLIC_BING_VERIFICATION
    ? { other: { "msvalidate.01": process.env.NEXT_PUBLIC_BING_VERIFICATION } }
    : {}),
};

/* Site-wide defaults. Every public page overrides title, description and the
   canonical URL through lib/seo.ts. The social card is app/opengraph-image.png
   (generated by `npm run generate:brand`), referenced explicitly here and in
   lib/seo.ts because a page-level openGraph block replaces this one. */
export const metadata: Metadata = {
  metadataBase: new URL(`${SITE_URL}/`),
  title: {
    default: SITE_TITLE,
    template: `%s · ${SITE_NAME}`,
  },
  description: SITE_DESCRIPTION,
  applicationName: SITE_NAME,
  keywords: [
    "GPU cloud Nepal",
    "AI cloud Nepal",
    "H100 Kathmandu",
    "H200 Nepal",
    "sovereign AI infrastructure",
    "GPU rental Nepal",
    "NPR GPU billing",
    "data residency Nepal",
    "JupyterHub GPU",
    "LLM inference Nepal",
  ],
  authors: [{ name: ORG.name, url: `${SITE_URL}/` }],
  creator: ORG.name,
  publisher: ORG.legalName,
  category: "technology",
  formatDetection: { email: false, address: false, telephone: false },
  alternates: { canonical: `${SITE_URL}/` },
  openGraph: {
    type: "website",
    siteName: SITE_NAME,
    locale: "en_US",
    url: `${SITE_URL}/`,
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    images: [SOCIAL_IMAGE],
  },
  twitter: {
    card: "summary_large_image",
    title: SITE_TITLE,
    description: SITE_DESCRIPTION,
    images: [SOCIAL_IMAGE.url],
  },
  robots: {
    index: true,
    follow: true,
    googleBot: { index: true, follow: true, "max-image-preview": "large", "max-snippet": -1 },
  },
  ...(Object.keys(verification).length ? { verification } : {}),
};

/* The mobile browser chrome starts paper (light is the default); the theme
   bootstrap below and lib/theme.ts rewrite this meta when a dark choice is
   saved. `color-scheme` (scrollbars, form controls) is set per theme in
   app/theme.css rather than here, so it follows the toggle and not the OS. */
export const viewport: Viewport = {
  themeColor: THEME_COLOR.light,
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${manrope.variable} ${jetbrainsMono.variable}`}
      suppressHydrationWarning
    >
      {/* No bg/text utilities needed: design_system/tokens/base.css (imported
          into layer(base)) already sets --bg-base, --text-primary and the
          Manrope 300 / 1.6 body defaults. */}
      <body className="min-h-dvh antialiased">
        {/* Theme bootstrap: stamps <html data-theme> from the saved choice or
            the OS preference before anything below paints, so the first frame
            is already the right theme. First in <body> rather than in <head>
            so it runs after <html> exists and before any content. */}
        <script dangerouslySetInnerHTML={{ __html: THEME_BOOTSTRAP }} />

        {/* Organisation and site graph, once, for every page. Pages add their
            own nodes (FAQ, Service, breadcrumbs) beside it. */}
        <JsonLd data={[organizationJsonLd(), webSiteJsonLd()]} />

        {/* Keyboard users land here first. Visually hidden until focused, at
            which point it becomes a real, fully styled control — a skip link
            that stays invisible when focused is worse than none. */}
        <a
          href="#main"
          className="sr-only focus:not-sr-only focus:fixed focus:top-4 focus:left-4 focus:z-[9999] focus:rounded-md focus:bg-hydro focus:px-4 focus:py-2.5 focus:font-mono focus:text-xs focus:tracking-label focus:text-on-hydro focus:uppercase"
        >
          Skip to content
        </a>

        {/* The scroll-reveal system hides content until JS marks it shown. If
            scripting is off, the `.cv-js` gate in CSS never arms — but a user
            with JS disabled mid-session would still be left with blank
            sections, so this unhides them unconditionally. */}
        <noscript>
          <style>{`[data-reveal]{opacity:1!important;transform:none!important}`}</style>
        </noscript>

        {/* Definitions-only SVG for the glass refraction pass. */}
        <LiquidFilters />

        {children}
      </body>
    </html>
  );
}
