import type { MetadataRoute } from "next";
import { SITE_DESCRIPTION, SITE_NAME } from "@/lib/site";

/**
 * /manifest.webmanifest — name, colours and icons for "add to home screen"
 * and for browsers that surface the app identity. Icons are generated by
 * `npm run generate:brand` (scripts/generate-brand-images.mjs).
 */
export const dynamic = "force-static";

const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: `${SITE_NAME} — Nepal's sovereign AI cloud`,
    short_name: SITE_NAME,
    description: SITE_DESCRIPTION,
    start_url: `${BASE}/`,
    scope: `${BASE}/`,
    display: "minimal-ui",
    background_color: "#05080D",
    theme_color: "#05080D",
    lang: "en",
    icons: [
      { src: `${BASE}/icons/icon-192.png`, sizes: "192x192", type: "image/png" },
      { src: `${BASE}/icons/icon-512.png`, sizes: "512x512", type: "image/png" },
      {
        src: `${BASE}/icons/icon-512-maskable.png`,
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
